baseURL: "https://cameronewood.xyz/"
languageCode: "en-uk"
title: "Cameron Wood"
theme: "aerial"

params:
  name: "Cameron Wood"
  about: "Ardent Systems/Software/DevOps Engineer. With over 10 years of experience working in a variety of roles from Networks, Security, Systems, Software, Architecture, and Agile methodologies."
  copyright: "Cameron Wood"
  bg_scroll: "nope"
  favicon: "favicon.ico"
  social:
    - link: "https://github.com/cewood"
      icon: "github"
      medium: "Github"
    - link: "https://www.linkedin.com/in/cameronewood"
      icon: "linkedin"
      medium: "LinkedIn"
    - link: "https://stackoverflow.com/cv/cameronewood"
      icon: "stack-overflow"
      medium: "StackOverflow"
