baseURL: "https://cameronewood.xyz/"
languageCode: "en-uk"
disableRSS: false
enableRobotsTXT: true
title: "Cameron Wood"
theme: "vncnt-hugo"

params:
  author: "Cameron Wood"
  description: "Landing Page"
  bio: "Ardent Engineering Leader adept at Systems, Software, Security, DevOps, and Cloud Native Engineering. With over 15 years of experience working in a variety of roles from Networks, Security, Systems, Software, Architecture, and Agile methodologies."
  avatar: "avatar.jpg"
  favicon: "favicon.ico"
  error404: "There is no such page."

  contacts:
    - name: github
      icon: fab fa-github
      link: "https://github.com/cewood"
    - name: linkedin
      icon: fab fa-linkedin
      link: "https://www.linkedin.com/in/cameronewood"
    - name: stack-overflow
      icon: fab fa-stack-overflow
      link: "https://stackoverflow.com/cv/cameronewood"
    - name: resume pdf
      icon: fa fa-file-pdf
      link: "https://cameronewood.xyz/cameronewood_cv.pdf"
