baseURL: "https://cameronewood.xyz/"
languageCode: "en-uk"
disableRSS: false
enableRobotsTXT: true
title: "Cameron Wood"
theme: "vncnt-hugo"

params:
  author: "Cameron Wood"
  description: "Landing Page"
  bio: "Ardent Systems/Software/DevOps Engineer. With over 10 years of experience working in a variety of roles from Networks, Security, Systems, Software, Architecture, and Agile methodologies."
  avatar: "avatar.jpg"
  favicon: "favicon.ico"
  error404: "There is no such page."

  contact:
    github: "https://github.com/cewood"
    linkedin: "https://www.linkedin.com/in/cameronewood"
    stack-overflow: "https://stackoverflow.com/cv/cameronewood"
